<!DOCTYPE html>
<html>
<head>
	<title>CrusaderMeme</title>
	<script src="//ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
	<style>
	/* Generated by Font Squirrel (http://www.fontsquirrel.com) on February 14, 2014 */

	@font-face {
		font-family: 'goudy_trajan_regularregular';
		src: url('fonts/goudytrajan-regular-trial-webfont.eot');
		src: url('fonts/goudytrajan-regular-trial-webfont.eot?#iefix') format('embedded-opentype'),
			 url('fonts/goudytrajan-regular-trial-webfont.woff') format('woff'),
			 url('fonts/goudytrajan-regular-trial-webfont.ttf') format('truetype'),
			 url('fonts/goudytrajan-regular-trial-webfont.svg#goudy_trajan_regularregular') format('svg');
		font-weight: normal;
		font-style: normal;

	}

	@font-face {
		font-family: 'trajanbold';
		src: url('fonts/trajan_bold-webfont.eot');
		src: url('fonts/trajan_bold-webfont.eot?#iefix') format('embedded-opentype'),
			 url('fonts/trajan_bold-webfont.woff') format('woff'),
			 url('fonts/trajan_bold-webfont.ttf') format('truetype'),
			 url('fonts/trajan_bold-webfont.svg#trajanbold') format('svg');
		font-weight: normal;
		font-style: normal;

	}
		
	html {
		background: black;
	}
	
	#event {
	  margin: 7% auto 0;
	  width: 500px;
	  position: relative;
	}

	#e_image {
	  position: absolute;
	  top: 61px;
	  left: 27px;
	}

	#e_text {
	  position: absolute;
	  top: 260px;
	  left: 80px;
	  width: 350px;
	  font-size: 14pt;
	  font-family: "trajanbold", "serif";
	  letter-spacing: -1px;
	}

	#e_options {
	  width: 476px;
	  margin: 0 auto;
	  position: absolute;
	  top: 438px;
	  left: 14px;
	}

	#e_options ul {
	  list-style: none;
	  padding: 0px !important;
	  margin: 0px auto !important;
	}

	#e_options li.e_option {
	  margin: 0px auto !important;
	  background: url("image.php?r=dOption") no-repeat;
	  height: 18px;
	  padding: 9px 20px;
	  text-transform: uppercase;
	  font-variant: small-caps;
	  font-family: "trajanbold", "serif";
	  letter-spacing: -1px;
	}
	
	ul#event_pictures:before {
	  content: "Choose a new event image";
	  color: white;
	  font-size: 24pt;
	  border-bottom: 1px solid white;
	  display: block;
	  text-align: center;
	  padding-bottom: 15px;
	  margin-bottom: 20px;
	  font-style: italic;
	  font-family: "trajanbold";
	}
	ul#event_pictures {
	  position: fixed;
	  z-index: 999;
	  background: rgba(0,0,0,0.7);
	  width: 100%;
	  height: 100%;
	  display: block;
	  top: 0px;
	  left; 0px;
	}
	ul#event_pictures li {
	  color: white;
	  display: block;
	  float: left;
	  width: 200px;
	  padding: 5px;
	  background: rgba(0,0,0,0.2);
	  margin: 2px;
	  overflow: hidden;
	  font-family: sans-serif;
	  font-size: 12px;
	  cursor: pointer;
	}
	ul#event_pictures li:hover {
	  background: rgba(50,50,50,0.2);
	}
	
	#e_image, #e_text, #e_options li {
		cursor: pointer;
	}
	
	button, input {
	  border: 1px solid #333;
	  background: black;
	  color: #555;
	  padding: 10px;
	  cursor: pointer;
	  display: inline-block !important;
	  clear: none;
	}
	#control_panel {
	  margin-top: 10px;
	  text-align: center;
	}
	
	#instructions {
	  color: #555;
	  font-size: 11px;
	  content: "Test";
	  font-family: sans-serif;
	  text-align: center;
	  width: 500px;
	}
	
	form {
	  display: inline-block;
	}
	
	body:before {
	  content: "CrusaderMemes";
	  color: #111;
	  font-family: sans-serif;
	  font-weight: bold;
	  font-size: 20pt;
	  text-align: center;
	  width: 100%;
	  display: block;
	  position: absolute;
	  top: 1%;
	  letter-spacing: -3px;
	}
	</style>
</head>
<?
	if(isset($_GET['i']))
		$e_image = $_GET['i'];
	else
		$e_image = "Courtiers_looking_scandalized.dds";
		
	if(isset($_GET['b']))
		$e_text = $_GET['b'];
	else
		$e_text = "Your rendevous with the coffee machine has ended in tears. It's broken and can't be used. Heresy!";
		
	if(isset($_GET['o'])) {
		$e_options = explode("###",$_GET['o']);
		//array_filter($linksArray);
	} else {
		$e_options = [
			"Give it a good tumble",
			"Have the peasants fill it with rocks",
			"I will deal with this myself!"
		];
	}
?>
<body>
<div id="wrapper">
	<ul id='event_pictures'></ul>
	<div id="event">
		<div id='instructions'>
			Click the image, text and options to change them. Or give 'em a good tumble.
		</div>
		<img id="e_panel" src="image.php?r=dPanel" />
		<img id="e_image" data-img-name='<?=$e_image ?>' src="image.php?r=event_pictures/<?=$e_image ?>" />
		<div id="e_text"><?=$e_text ?></div>
		<? 
		switch(count($e_options)) {
			case 1: break;
			case 2: ?><img id="e_panel_extension" style="margin-top: -80px;" src="image.php?r=dExtensionBottom" /><? break;
			case 3: ?><img id="e_panel_extension" style="margin-top: -50px;" src="image.php?r=dExtensionBottom" /><? break;
		}
		?>
		<div id="e_options">
			<ul>
			<?
			foreach($e_options as $option) {
			?>
				<li class="e_option"><?=$option ?></li>
			<?
			}
			?>
			</ul>
		</div>
		<div id="control_panel">
			<button id="share_url" data-clipboard-text="http://jan.baykara.co.uk/projects/crusadermemes/" title="Click to copy me.">Share URL</button>
			<form id='reset_event' action="http://jan.baykara.co.uk/projects/crusadermemes">
				<input type="submit" value="Reset">
			</form>
			<!--<button id="random_event">User Created Events</button>-->
			<button>User Created Events viewing temporarily disabled due to obscene content, by request of Paradox.</button>
		</div>
		<div id='debug_bin'></div>
	</div>
</div>
<script>
	$('#e_text, #e_options li').mouseup(function() {
		var newEText = prompt("Event text",$(this).text());
		if (newEText != null) {
			$(this).text(newEText);
		}
	});
	
	$('#event_pictures').hide();
	
	$('#e_image').mouseup(function() {
		$.ajax({
		  url: "img/event_pictures/",
		  success: function(data){
			 $(data).find("a:contains(.dds)").each(function(){
				// will loop through 
				var images = $(this).attr("href");
				$('<li>').html(images).appendTo($('#event_pictures'));
				$('#event_pictures').show();
			 });
				
			$('#event_pictures li').mouseup(function() {
				var newImageURL = "image.php?r=event_pictures/"+$(this).text();
				$("#e_image").attr("data-img-name",$(this).text());
				$("#e_image").attr("src",newImageURL);
				$('#event_pictures').empty();
				$('#event_pictures').hide();
			});
		  }
		});
	});
	
	$('#share_url').mouseup(function() {
		var bodyText = encodeURIComponent($('#e_text').text());
		var options = "###";
		$.each($('#e_options li'), function() {
			options += "###"+$(this).text();
		});
		options = encodeURIComponent(options.substring(6));
		var image = encodeURIComponent($('#e_image').attr('data-img-name'));
		
		var shareURL = "http://jan.baykara.co.uk/projects/crusadermemes/?b="+bodyText+"&o="+options+"&i="+image;
		$(this).attr("data-clipboard-text",shareURL);
		
		$.get( "tinyurl.php?u="+encodeURIComponent(shareURL), function( data ) {
			var tinyURL = data;
			prompt ("Here's your share link, squire. Give it a good tumble.", tinyURL);
		});
	});
	
	$('#random_event').click(function() {
		$.get("memelog.txt", function(memelog) {
			var urls = memelog.split("\n");
			var idx = Math.floor(urls.length * Math.random());
			window.open(urls[idx],'_top');
		});
	});
</script>
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-47411407-1', 'baykara.co.uk');
  ga('send', 'pageview');
</script>
</body>
</html>